# Generated by Django 2.0.5 on 2018-05-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='You can add notes'),
            preserve_default=False,
        ),
    ]
